[application]

name = "Dumb Slut"
version = "0.0.1"
authors = ["Pavel Kiselev <kpashka@gmail.com>"]

[dependencies]

"github.com/jteeuwen/go-pkg-rss" = "master"
"github.com/nlopes/slack" = "master"
"github.com/Sirupsen/logrus" = "master"
"github.com/tucnak/telebot" = "master"
"golang.org/x/exp" = "master"